@startuml

namespace Spider {

namespace Core {

    class Spider {
        +Spider()
        +~Spider()
        ..
 		+void	run()
 		..
 		-void	keyLogger(EventQueue)
 		-void   network(EventQueue)
 	}

 	class   KeyReader {
 	    -mSaveX : int
 	    -mSaveY : int
 	    -mOld : string
 	    -mActivity : string
 	    __
 	    +KeyReader()
 	    +~KeyReader()
 	    ..
        +oid 	    read(EventQueue)
        ..
        -ClickType	isClick(int)
        -ClickType	isMouseMove()
        -bool		isInvalidKey(int)
        -string	    findActivity()
 	}
}

}

@enduml